version: '3.9'
services:
  mysql_bd4:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: dbloja
    ports:
      - '3307:3306'
    volumes:
      - ./db_data:/var/lib/mysql
volumes:
  db_data: